"""OpenSCAD emission from the Python module.

We do NOT re-encode the whole alphabet in SCAD here: `scad/vacua_param.scad`
already contains the full table and the logic. We only emit a wrapper that
fixes the text and includes the parametric file.
"""

from __future__ import annotations

from pathlib import Path

# Default path to the parametric generator (adapt if moved).
DEFAULT_PARAM = "../scad/vacua_param.scad"


def write_scad(text: str, out: Path, param_path: str = DEFAULT_PARAM, **overrides: object) -> None:
    """Write a SCAD wrapper that parameterizes `vacua_param.scad` and includes it.

    `overrides` lets you override variables exposed by the generator:
    cell, bar_w, relief_h, base_h, cols_tiles, merged, with_keyring, puce_on, round_bars...
    """
    out.parent.mkdir(parents=True, exist_ok=True)
    lines: list[str] = [
        f'// Auto-generated by vacua.scad_emit for text: {text!r}',
        f'text = "{text.upper()}";',
    ]
    for key, val in overrides.items():
        if isinstance(val, bool):
            lines.append(f"{key} = {'true' if val else 'false'};")
        elif isinstance(val, (int, float)):
            lines.append(f"{key} = {val};")
        else:
            lines.append(f'{key} = "{val}";')
    lines.append(f'include <{param_path}>;')
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
